# Generated by Django 3.2 on 2023-04-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_played',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.PositiveSmallIntegerField(choices=[(1, '1/8 финал'), (2, '1/4 финал'), (3, '1/2 финал'), (4, '3-место'), (5, 'Финал')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Запланированный'), (2, 'Прямо сейчас'), (3, 'Завершенный')]),
        ),
        migrations.AlterField(
            model_name='teamcomposition',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'В стране'), (2, 'В гости')]),
        ),
    ]
