# Generated by Django 3.2 on 2023-04-10 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_match_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Побед хозяев'), (2, 'Побед гостей'), (3, 'Ничья')], default=1),
        ),
        migrations.CreateModel(
            name='TourmentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.team')),
                ('tourment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tournament')),
            ],
        ),
    ]
