# Generated by Django 3.2 on 2023-04-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20230410_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourmentteam',
            name='team',
        ),
        migrations.AddField(
            model_name='tourmentteam',
            name='team',
            field=models.ManyToManyField(to='main_app.Team'),
        ),
    ]
