# Generated by Django 3.2 on 2023-04-10 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_teamplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamplayer',
            name='team',
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.team'),
            preserve_default=False,
        ),
    ]
