# Generated by Django 3.2 on 2023-04-10 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20230411_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('goal', models.PositiveSmallIntegerField()),
                ('penalty', models.PositiveSmallIntegerField()),
                ('minut', models.PositiveSmallIntegerField()),
                ('game', models.PositiveSmallIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.player')),
                ('tourment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tournament')),
            ],
        ),
    ]
