# Generated by Django 3.2 on 2023-04-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_playerstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('name', models.CharField(max_length=250)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('matches', models.PositiveSmallIntegerField()),
                ('chief_judge', models.PositiveSmallIntegerField()),
                ('yellow_card', models.PositiveSmallIntegerField()),
                ('second_yellow_card', models.PositiveSmallIntegerField()),
                ('red_card', models.PositiveSmallIntegerField()),
                ('penalty', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('name', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('average_capacity', models.PositiveSmallIntegerField()),
                ('memorability', models.DecimalField(decimal_places=2, max_digits=8)),
                ('matches', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('name', models.CharField(max_length=250)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('team', models.CharField(max_length=100)),
                ('matches', models.PositiveSmallIntegerField()),
                ('wins', models.PositiveSmallIntegerField()),
                ('drows', models.PositiveSmallIntegerField()),
                ('defeats', models.PositiveSmallIntegerField()),
                ('points', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
