# Generated by Django 3.2 on 2023-04-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_judge_stadium_trainers'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='tourment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.tournament'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stadium',
            name='tourment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.tournament'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainers',
            name='tourment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.tournament'),
            preserve_default=False,
        ),
    ]
