# Generated by Django 4.2 on 2023-04-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20230411_0128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': 'Гол', 'verbose_name_plural': 'Голы'},
        ),
        migrations.AlterModelOptions(
            name='judge',
            options={'verbose_name': 'Судьия', 'verbose_name_plural': 'Судьи'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Матч', 'verbose_name_plural': 'Матчи'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='playerstatistics',
            options={'verbose_name': 'Статистика игрока', 'verbose_name_plural': 'Статистики игроков'},
        ),
        migrations.AlterModelOptions(
            name='stadium',
            options={'verbose_name': 'Стадион', 'verbose_name_plural': 'Стадионы'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterModelOptions(
            name='teamcomposition',
            options={'verbose_name': 'Состав', 'verbose_name_plural': 'Составы'},
        ),
        migrations.AlterModelOptions(
            name='teamplayer',
            options={'verbose_name': 'Командный игрок', 'verbose_name_plural': 'Командные игроки'},
        ),
        migrations.AlterModelOptions(
            name='tourmentteam',
            options={'verbose_name': 'Чемпионат мира', 'verbose_name_plural': 'Чемпионаты мира'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'Турнир', 'verbose_name_plural': 'Турниры'},
        ),
        migrations.AlterModelOptions(
            name='trainers',
            options={'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_penalty',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_penalty',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='is_penalty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teamcomposition',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Дома'), (2, 'В гости')]),
        ),
    ]
