# Generated by Django 4.2 on 2023-04-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_goal_options_alter_judge_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team_penalty',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_penalty',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
